name: SAMPIT
on: [push, pull_request]
jobs:
  build:
    name: BUILDS
    runs-on: ubuntu-18.04
    timeout-minutes: 50
    steps:
    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Checkout
      uses: actions/checkout@v1
    - name: run
      run: ifconfig
